# dependabot.yml
# Dependabot configuration file to manage automated dependency updates
# Jordan Carlin jcarlin@hmc.edu October 2025
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Update git submodules to latest version
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
  # Update actions in the GitHub Actions workflow files
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Update uv python packages
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
